<a href="https://colab.research.google.com/github/lauvsong/data-analysis-practice/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!dir

sample_data


In [ ]:
a = 1

In [ ]:
a

1

In [ ]:
%hist

!dir
a = 1
a
!hist
%hist


In [ ]:
%hist -g a = 1

   2: a = 1
   7: %hist -g a = 1


In [ ]:
print('c:\new folder')

c:
ew folder


In [ ]:
print(r'c:\new folder')

c:\new folder


In [ ]:
import numpy as np

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a.shape

(5,)

In [ ]:
m = np.array([np.arange(2), np.arange(2)])

In [ ]:
m.shape

(2, 2)

In [ ]:
m[0,0] = 0
m[1,0] = 1
m[0,1] = 2
m[1,1] = 3
m

array([[0, 2],
       [1, 3]])

In [ ]:
m + 2

array([[2, 4],
       [3, 5]])

In [ ]:
m * 2

array([[0, 4],
       [2, 6]])

In [ ]:
a[1:3]

array([1, 2])

In [ ]:
m[0,1:]

array([2])

In [ ]:
np.array([np.arange(3), np.arange(3)])

array([[0, 1, 2],
       [0, 1, 2]])

In [ ]:
arr1 = np.array([1,2,3], dtype=np.float)

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
arr1 = np.array([1.5, 1.2, 1.4], dtype=np.float)
arr1

array([1.5, 1.2, 1.4])

In [ ]:
arr1.astype(np.int)

array([1, 1, 1])

In [ ]:
mask = np.array([0,1,0,1,0,1,0], dtype=bool)
mask

array([False,  True, False,  True, False,  True, False])

In [ ]:
data = np.random.randn(7,4)
data

array([[-0.04992948,  0.09472136, -0.97741845, -0.14421985],
       [-0.77938508,  0.25984254,  0.12741191,  0.14166128],
       [-2.22622405, -0.90377969, -0.75593041,  0.81832245],
       [-0.80838281,  0.63721161, -0.02444502, -0.56048773],
       [-0.59165987, -0.29008712, -2.06139697,  0.50028874],
       [ 0.39860268, -0.71548529,  0.87022234,  1.50204696],
       [ 0.43239172, -0.04638129,  0.15002871, -0.40681262]])

In [ ]:
data[[1,2,3,4]]

array([[-0.77938508,  0.25984254,  0.12741191,  0.14166128],
       [-2.22622405, -0.90377969, -0.75593041,  0.81832245],
       [-0.80838281,  0.63721161, -0.02444502, -0.56048773],
       [-0.59165987, -0.29008712, -2.06139697,  0.50028874]])

In [ ]:
data[mask]

array([[-0.77938508,  0.25984254,  0.12741191,  0.14166128],
       [-0.80838281,  0.63721161, -0.02444502, -0.56048773],
       [ 0.39860268, -0.71548529,  0.87022234,  1.50204696]])

In [ ]:
data[~mask]

array([[-0.04992948,  0.09472136, -0.97741845, -0.14421985],
       [-2.22622405, -0.90377969, -0.75593041,  0.81832245],
       [-0.59165987, -0.29008712, -2.06139697,  0.50028874],
       [ 0.43239172, -0.04638129,  0.15002871, -0.40681262]])

In [ ]:
over0 = data[data>0]

In [ ]:
over1 = data[2][data[2] > 0]
over1

array([0.81832245])

In [ ]:
x = np.random.randint(1, 100, size=10)
x

array([21,  3, 11, 16, 47, 54, 15, 98, 50, 48])

In [ ]:
x[x % 2 == 0]

array([16, 54, 98, 50, 48])

In [ ]:
x[x > 30]

array([47, 54, 98, 50, 48])

In [ ]:
x[(x % 2 == 0) & (x < 30)]

array([16])

In [ ]:
x[(x < 30) | (x > 50)]

array([21,  3, 11, 16, 54, 15, 98])

In [ ]:
b = np.arange(24)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
b.shape = (6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
c = np.arange(0,25,3)
c

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [ ]:
c.shape = (3,3)
c

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [ ]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
c.ravel()

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [ ]:
c.flatten()

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [ ]:
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [ ]:
b.resize((2,12))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
b.shape

(2, 12)

In [ ]:
np.hstack([np.arange(8), np.arange(0,15,2)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  0,  2,  4,  6,  8, 10, 12, 14])

In [ ]:
np.vstack([np.arange(8), np.arange(0,22,3)])

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 0,  3,  6,  9, 12, 15, 18, 21]])

In [ ]:
np.dstack([np.arange(8),np.arange(0,50,7)])

array([[[ 0,  0],
        [ 1,  7],
        [ 2, 14],
        [ 3, 21],
        [ 4, 28],
        [ 5, 35],
        [ 6, 42],
        [ 7, 49]]])

In [ ]:
a = np.arange(9)
a.shape = (3,3)
np.hsplit(a,3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [ ]:
np.vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [ ]:
c = np.arange(27).reshape(3,3,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
np.dsplit(c,3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [ ]:
from sklearn import datasets

iris = datasets.load_iris()
irisdt = iris['data']

iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
irisdt

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
splen = irisdt[:,0]
splen

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [ ]:
ptlen = irisdt[:,2]
ptlen

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.4, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

In [ ]:
irisdt[[3,5],:]

array([[4.6, 3.1, 1.5, 0.2],
       [5.4, 3.9, 1.7, 0.4]])